/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as RouteRouteImport } from './routes/route'
import { Route as LoginSignupRouteRouteImport } from './routes/login/signup/route'
import { Route as LoginSigninRouteRouteImport } from './routes/login/signin/route'
import { Route as HomeDashboardRouteRouteImport } from './routes/home/dashboard/route'
import { Route as HomeUserIndexRouteImport } from './routes/home/user/index'
import { Route as HomeUserWriteRouteImport } from './routes/home/user/write'

const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteRoute = RouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSignupRouteRoute = LoginSignupRouteRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => LoginRouteRoute,
} as any)
const LoginSigninRouteRoute = LoginSigninRouteRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => LoginRouteRoute,
} as any)
const HomeDashboardRouteRoute = HomeDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeUserIndexRoute = HomeUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeUserWriteRoute = HomeUserWriteRouteImport.update({
  id: '/user/write',
  path: '/user/write',
  getParentRoute: () => HomeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/home': typeof HomeRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/home/dashboard': typeof HomeDashboardRouteRoute
  '/login/signin': typeof LoginSigninRouteRoute
  '/login/signup': typeof LoginSignupRouteRoute
  '/home/user/write': typeof HomeUserWriteRoute
  '/home/user': typeof HomeUserIndexRoute
}
export interface FileRoutesByTo {
  '/home': typeof HomeRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/home/dashboard': typeof HomeDashboardRouteRoute
  '/login/signin': typeof LoginSigninRouteRoute
  '/login/signup': typeof LoginSignupRouteRoute
  '/home/user/write': typeof HomeUserWriteRoute
  '/home/user': typeof HomeUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof RouteRoute
  '/home': typeof HomeRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/home/dashboard': typeof HomeDashboardRouteRoute
  '/login/signin': typeof LoginSigninRouteRoute
  '/login/signup': typeof LoginSignupRouteRoute
  '/home/user/write': typeof HomeUserWriteRoute
  '/home/user/': typeof HomeUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/home'
    | '/login'
    | '/home/dashboard'
    | '/login/signin'
    | '/login/signup'
    | '/home/user/write'
    | '/home/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/home'
    | '/login'
    | '/home/dashboard'
    | '/login/signin'
    | '/login/signup'
    | '/home/user/write'
    | '/home/user'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/login'
    | '/home/dashboard'
    | '/login/signin'
    | '/login/signup'
    | '/home/user/write'
    | '/home/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RouteRoute: typeof RouteRoute
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/signup': {
      id: '/login/signup'
      path: '/signup'
      fullPath: '/login/signup'
      preLoaderRoute: typeof LoginSignupRouteRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/login/signin': {
      id: '/login/signin'
      path: '/signin'
      fullPath: '/login/signin'
      preLoaderRoute: typeof LoginSigninRouteRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/home/dashboard': {
      id: '/home/dashboard'
      path: '/dashboard'
      fullPath: '/home/dashboard'
      preLoaderRoute: typeof HomeDashboardRouteRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/user/': {
      id: '/home/user/'
      path: '/user'
      fullPath: '/home/user'
      preLoaderRoute: typeof HomeUserIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/home/user/write': {
      id: '/home/user/write'
      path: '/user/write'
      fullPath: '/home/user/write'
      preLoaderRoute: typeof HomeUserWriteRouteImport
      parentRoute: typeof HomeRouteRoute
    }
  }
}

interface HomeRouteRouteChildren {
  HomeDashboardRouteRoute: typeof HomeDashboardRouteRoute
  HomeUserWriteRoute: typeof HomeUserWriteRoute
  HomeUserIndexRoute: typeof HomeUserIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeDashboardRouteRoute: HomeDashboardRouteRoute,
  HomeUserWriteRoute: HomeUserWriteRoute,
  HomeUserIndexRoute: HomeUserIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

interface LoginRouteRouteChildren {
  LoginSigninRouteRoute: typeof LoginSigninRouteRoute
  LoginSignupRouteRoute: typeof LoginSignupRouteRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginSigninRouteRoute: LoginSigninRouteRoute,
  LoginSignupRouteRoute: LoginSignupRouteRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RouteRoute: RouteRoute,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
